name: bikenwloops
channels:
  - conda-forge
  - defaults
dependencies:
  - access=1.1.9
  - affine=2.4.0
  - aiobotocore=2.23.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - amply=0.1.6
  - appnope=0.1.4
  - arm_pyart=2.1.0
  - arpack=3.8.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - beautifulsoup4=4.12.3
  - blosc=1.21.6
  - bokeh=3.7.3
  - botocore=1.39.8
  - branca=0.7.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - capnproto=1.2.0
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cffi=1.16.0
  - cfgv=3.3.1
  - cfitsio=4.6.2
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - cmweather=0.3.2
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cpython=3.12.11
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2025.7.0
  - dask-core=2025.7.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - deprecation=2.1.0
  - distlib=0.3.8
  - distributed=2025.7.0
  - docutils=0.22
  - esda=2.7.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.7.1
  - filelock=3.13.1
  - fiona=1.10.1
  - flexcache=0.3
  - flexparser=0.4
  - fmt=11.2.0
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.13.3
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gdal=3.10.3
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - geotiff=1.7.4
  - gettext=0.21.1
  - gflags=2.2.2
  - giddy=2.3.6
  - giflib=5.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h3=4.3.0
  - h3-py=4.3.0
  - h3pandas=0.3.0
  - h5netcdf=1.6.3
  - h5py=3.14.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - identify=2.5.35
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - inequality=1.1.2
  - iniconfig=2.0.0
  - ipykernel=6.29.2
  - ipython=8.21.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.3.2
  - json-c=0.18
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyterlab_widgets=3.0.13
  - kealib=1.6.2
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lat_lon_parser=1.3.1
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgdal=3.10.3
  - libgdal-core=3.10.3
  - libgdal-fits=3.10.3
  - libgdal-grib=3.10.3
  - libgdal-hdf4=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-jp2openjpeg=3.10.3
  - libgdal-kea=3.10.3
  - libgdal-netcdf=3.10.3
  - libgdal-pdf=3.10.3
  - libgdal-pg=3.10.3
  - libgdal-postgisraster=3.10.3
  - libgdal-tiledb=3.10.3
  - libgdal-xls=3.10.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libopenblas=0.3.26
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=6.31.1
  - libpysal=4.13.0
  - libre2-11=2025.07.22
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=17.0.6
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mda-xdrlib=0.2.0
  - mgwr=2.2.1
  - minizip=4.0.10
  - momepy=0.11.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - munkres=1.1.4
  - narwhals=2.0.1
  - ncurses=6.5
  - neatnet=0.1.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - nodeenv=1.8.0
  - nspr=4.37
  - nss=3.114
  - numba=0.59.0
  - numpy=1.26.4
  - open-radar-data=0.5.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - orc=2.2.0
  - packaging=23.2
  - pandas=2.2.3
  - parso=0.8.3
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pint=0.24.4
  - pip=24.0
  - pixman=0.46.4
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pointpats=2.5.1
  - pooch=1.8.2
  - poppler=25.07.0
  - poppler-data=0.4.12
  - postgresql=17.5
  - pre-commit=3.6.2
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.42
  - propcache=0.3.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.8.0
  - pure_eval=0.2.2
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyogrio=0.11.0
  - pyparsing=3.1.1
  - pyproj=3.7.1
  - pysal=25.7
  - pyshp=3.0.0
  - pysocks=1.7.1
  - pytest=8.0.0
  - python=3.12.11
  - python-dateutil=2.8.2
  - python-igraph=0.11.5
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - quantecon=0.8.2
  - rasterio=1.4.3
  - rasterstats=0.20.0
  - re2=2025.07.22
  - readline=8.2
  - requests=2.31.0
  - rtree=1.2.0
  - s3fs=2025.7.0
  - scikit-learn=1.4.1.post1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - segregation=2.5.2
  - setuptools=69.1.0
  - setuptools-scm=8.3.1
  - setuptools_scm=8.3.1
  - shapely=2.1.1
  - simplejson=3.20.1
  - six=1.16.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spaghetti=1.7.6
  - spdlog=1.15.3
  - spglm=1.1.0
  - spint=1.0.7
  - splot=1.1.7
  - spopt=0.7.0
  - spreg=1.8.3
  - spvcm=0.3.0
  - sqlite=3.50.4
  - stack_data=0.6.2
  - statsmodels=0.14.5
  - sympy=1.14.0
  - tblib=3.1.0
  - texttable=1.7.0
  - threadpoolctl=3.3.0
  - tiledb=2.28.1
  - tk=8.6.13
  - tobler=0.12.1
  - tomli=2.0.1
  - toolz=1.0.0
  - tornado=6.4
  - tqdm=4.66.5
  - traitlets=5.14.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzcode=2024a
  - tzdata=2024a
  - ukkonen=1.0.1
  - uriparser=0.9.8
  - urllib3=2.2.1
  - versioneer=0.29
  - virtualenv=20.25.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - xarray=2025.6.1
  - xerces-c=3.2.5
  - xmltodict=0.14.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xradar=0.10.0
  - xyzservices=2023.10.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /Users/mszell/miniforge3/envs/bikenwloops
